[Service]
ExecStart=
ExecStart=/usr/bin/krdpserver --address 172.18.0.1 --port 3389 --username zahranm --password "GgSGgxSpYmSsVQltN7CN" --quality 80 --certificate /home/zahranm/.config/krdp/cert.pem --certificate-key /home/zahranm/.config/krdp/key.pem --plasma
Environment="QT_LOGGING_RULES=krdp.debug=true;krdpserver.debug=true"
